// Generated by gencpp from file mapping_msgs/FindObjects.msg
// DO NOT EDIT!


#ifndef MAPPING_MSGS_MESSAGE_FINDOBJECTS_H
#define MAPPING_MSGS_MESSAGE_FINDOBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace mapping_msgs
{
template <class ContainerAllocator>
struct FindObjects_
{
  typedef FindObjects_<ContainerAllocator> Type;

  FindObjects_()
    : name()
    , near_to()
    , nearest_to_robot(false)
    , near_to_position()  {
    }
  FindObjects_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , near_to(_alloc)
    , nearest_to_robot(false)
    , near_to_position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _near_to_type;
  _near_to_type near_to;

   typedef uint8_t _nearest_to_robot_type;
  _nearest_to_robot_type nearest_to_robot;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _near_to_position_type;
  _near_to_position_type near_to_position;





  typedef boost::shared_ptr< ::mapping_msgs::FindObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapping_msgs::FindObjects_<ContainerAllocator> const> ConstPtr;

}; // struct FindObjects_

typedef ::mapping_msgs::FindObjects_<std::allocator<void> > FindObjects;

typedef boost::shared_ptr< ::mapping_msgs::FindObjects > FindObjectsPtr;
typedef boost::shared_ptr< ::mapping_msgs::FindObjects const> FindObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapping_msgs::FindObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapping_msgs::FindObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mapping_msgs::FindObjects_<ContainerAllocator1> & lhs, const ::mapping_msgs::FindObjects_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.near_to == rhs.near_to &&
    lhs.nearest_to_robot == rhs.nearest_to_robot &&
    lhs.near_to_position == rhs.near_to_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mapping_msgs::FindObjects_<ContainerAllocator1> & lhs, const ::mapping_msgs::FindObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mapping_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mapping_msgs::FindObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapping_msgs::FindObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping_msgs::FindObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping_msgs::FindObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping_msgs::FindObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping_msgs::FindObjects_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapping_msgs::FindObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8b330e3732aff29a86332e860a858d8";
  }

  static const char* value(const ::mapping_msgs::FindObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8b330e3732aff29ULL;
  static const uint64_t static_value2 = 0xa86332e860a858d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapping_msgs::FindObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapping_msgs/FindObjects";
  }

  static const char* value(const ::mapping_msgs::FindObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapping_msgs::FindObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string near_to\n"
"bool nearest_to_robot\n"
"geometry_msgs/Point near_to_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mapping_msgs::FindObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapping_msgs::FindObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.near_to);
      stream.next(m.nearest_to_robot);
      stream.next(m.near_to_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapping_msgs::FindObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapping_msgs::FindObjects_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "near_to: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.near_to);
    s << indent << "nearest_to_robot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nearest_to_robot);
    s << indent << "near_to_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.near_to_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPPING_MSGS_MESSAGE_FINDOBJECTS_H
