// Generated by gencpp from file mapping_msgs/SemanticObject.msg
// DO NOT EDIT!


#ifndef MAPPING_MSGS_MESSAGE_SEMANTICOBJECT_H
#define MAPPING_MSGS_MESSAGE_SEMANTICOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>
#include <geometry_msgs/Polygon.h>
#include <geometry_msgs/Point.h>
#include <sensor_msgs/PointCloud2.h>

namespace mapping_msgs
{
template <class ContainerAllocator>
struct SemanticObject_
{
  typedef SemanticObject_<ContainerAllocator> Type;

  SemanticObject_()
    : id(0)
    , shape()
    , obb()
    , position()
    , pointcloud()
    , name()
    , tags()
    , confidence()
    , exist_certainty(0.0)  {
    }
  SemanticObject_(const ContainerAllocator& _alloc)
    : id(0)
    , shape(_alloc)
    , obb(_alloc)
    , position(_alloc)
    , pointcloud(_alloc)
    , name(_alloc)
    , tags(_alloc)
    , confidence(_alloc)
    , exist_certainty(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _shape_type;
  _shape_type shape;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _obb_type;
  _obb_type obb;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _tags_type;
  _tags_type tags;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _confidence_type;
  _confidence_type confidence;

   typedef double _exist_certainty_type;
  _exist_certainty_type exist_certainty;





  typedef boost::shared_ptr< ::mapping_msgs::SemanticObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapping_msgs::SemanticObject_<ContainerAllocator> const> ConstPtr;

}; // struct SemanticObject_

typedef ::mapping_msgs::SemanticObject_<std::allocator<void> > SemanticObject;

typedef boost::shared_ptr< ::mapping_msgs::SemanticObject > SemanticObjectPtr;
typedef boost::shared_ptr< ::mapping_msgs::SemanticObject const> SemanticObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapping_msgs::SemanticObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapping_msgs::SemanticObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mapping_msgs::SemanticObject_<ContainerAllocator1> & lhs, const ::mapping_msgs::SemanticObject_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.shape == rhs.shape &&
    lhs.obb == rhs.obb &&
    lhs.position == rhs.position &&
    lhs.pointcloud == rhs.pointcloud &&
    lhs.name == rhs.name &&
    lhs.tags == rhs.tags &&
    lhs.confidence == rhs.confidence &&
    lhs.exist_certainty == rhs.exist_certainty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mapping_msgs::SemanticObject_<ContainerAllocator1> & lhs, const ::mapping_msgs::SemanticObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mapping_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapping_msgs::SemanticObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapping_msgs::SemanticObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapping_msgs::SemanticObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34c4e8ec6dbe8338ce914b56f57b64e4";
  }

  static const char* value(const ::mapping_msgs::SemanticObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34c4e8ec6dbe8338ULL;
  static const uint64_t static_value2 = 0xce914b56f57b64e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapping_msgs/SemanticObject";
  }

  static const char* value(const ::mapping_msgs::SemanticObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"geometry_msgs/Polygon shape\n"
"geometry_msgs/Polygon obb\n"
"geometry_msgs/Point position # should be centroid of shape\n"
"sensor_msgs/PointCloud2 pointcloud\n"
"string name\n"
"string[] tags\n"
"float64[] confidence\n"
"float64 exist_certainty\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::mapping_msgs::SemanticObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.shape);
      stream.next(m.obb);
      stream.next(m.position);
      stream.next(m.pointcloud);
      stream.next(m.name);
      stream.next(m.tags);
      stream.next(m.confidence);
      stream.next(m.exist_certainty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SemanticObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapping_msgs::SemanticObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapping_msgs::SemanticObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "shape: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.shape);
    s << indent << "obb: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.obb);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tags[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.confidence[i]);
    }
    s << indent << "exist_certainty: ";
    Printer<double>::stream(s, indent + "  ", v.exist_certainty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPPING_MSGS_MESSAGE_SEMANTICOBJECT_H
