// Generated by gencpp from file hypermap_msgs/GetIntAtPointResponse.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETINTATPOINTRESPONSE_H
#define HYPERMAP_MSGS_MESSAGE_GETINTATPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hypermap_msgs
{
template <class ContainerAllocator>
struct GetIntAtPointResponse_
{
  typedef GetIntAtPointResponse_<ContainerAllocator> Type;

  GetIntAtPointResponse_()
    : value(0)  {
    }
  GetIntAtPointResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIntAtPointResponse_

typedef ::hypermap_msgs::GetIntAtPointResponse_<std::allocator<void> > GetIntAtPointResponse;

typedef boost::shared_ptr< ::hypermap_msgs::GetIntAtPointResponse > GetIntAtPointResponsePtr;
typedef boost::shared_ptr< ::hypermap_msgs::GetIntAtPointResponse const> GetIntAtPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hypermap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hypermap_msgs/GetIntAtPointResponse";
  }

  static const char* value(const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n"
"\n"
;
  }

  static const char* value(const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIntAtPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hypermap_msgs::GetIntAtPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETINTATPOINTRESPONSE_H
