// Generated by gencpp from file hypermap_msgs/GetIntsByArea.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETINTSBYAREA_H
#define HYPERMAP_MSGS_MESSAGE_GETINTSBYAREA_H

#include <ros/service_traits.h>


#include <hypermap_msgs/GetIntsByAreaRequest.h>
#include <hypermap_msgs/GetIntsByAreaResponse.h>


namespace hypermap_msgs
{

struct GetIntsByArea
{

typedef GetIntsByAreaRequest Request;
typedef GetIntsByAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIntsByArea
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::GetIntsByArea > {
  static const char* value()
  {
    return "31e81242de76615a7f403b97dc514350";
  }

  static const char* value(const ::hypermap_msgs::GetIntsByArea&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::GetIntsByArea > {
  static const char* value()
  {
    return "hypermap_msgs/GetIntsByArea";
  }

  static const char* value(const ::hypermap_msgs::GetIntsByArea&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::GetIntsByAreaRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetIntsByArea >
template<>
struct MD5Sum< ::hypermap_msgs::GetIntsByAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetIntsByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetIntsByAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetIntsByAreaRequest> should match
// service_traits::DataType< ::hypermap_msgs::GetIntsByArea >
template<>
struct DataType< ::hypermap_msgs::GetIntsByAreaRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetIntsByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetIntsByAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::GetIntsByAreaResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetIntsByArea >
template<>
struct MD5Sum< ::hypermap_msgs::GetIntsByAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetIntsByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetIntsByAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetIntsByAreaResponse> should match
// service_traits::DataType< ::hypermap_msgs::GetIntsByArea >
template<>
struct DataType< ::hypermap_msgs::GetIntsByAreaResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetIntsByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetIntsByAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETINTSBYAREA_H
