// Generated by gencpp from file hypermap_msgs/GetLocationsByString.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRING_H
#define HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRING_H

#include <ros/service_traits.h>


#include <hypermap_msgs/GetLocationsByStringRequest.h>
#include <hypermap_msgs/GetLocationsByStringResponse.h>


namespace hypermap_msgs
{

struct GetLocationsByString
{

typedef GetLocationsByStringRequest Request;
typedef GetLocationsByStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLocationsByString
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::GetLocationsByString > {
  static const char* value()
  {
    return "f35d753aab50372861c2fe00912379e5";
  }

  static const char* value(const ::hypermap_msgs::GetLocationsByString&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::GetLocationsByString > {
  static const char* value()
  {
    return "hypermap_msgs/GetLocationsByString";
  }

  static const char* value(const ::hypermap_msgs::GetLocationsByString&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::GetLocationsByStringRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetLocationsByString >
template<>
struct MD5Sum< ::hypermap_msgs::GetLocationsByStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetLocationsByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetLocationsByStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetLocationsByStringRequest> should match
// service_traits::DataType< ::hypermap_msgs::GetLocationsByString >
template<>
struct DataType< ::hypermap_msgs::GetLocationsByStringRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetLocationsByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetLocationsByStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::GetLocationsByStringResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetLocationsByString >
template<>
struct MD5Sum< ::hypermap_msgs::GetLocationsByStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetLocationsByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetLocationsByStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetLocationsByStringResponse> should match
// service_traits::DataType< ::hypermap_msgs::GetLocationsByString >
template<>
struct DataType< ::hypermap_msgs::GetLocationsByStringResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetLocationsByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetLocationsByStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRING_H
