// Generated by gencpp from file hypermap_msgs/GetLocationsByStringResponse.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRINGRESPONSE_H
#define HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace hypermap_msgs
{
template <class ContainerAllocator>
struct GetLocationsByStringResponse_
{
  typedef GetLocationsByStringResponse_<ContainerAllocator> Type;

  GetLocationsByStringResponse_()
    : locations()  {
    }
  GetLocationsByStringResponse_(const ContainerAllocator& _alloc)
    : locations(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _locations_type;
  _locations_type locations;





  typedef boost::shared_ptr< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetLocationsByStringResponse_

typedef ::hypermap_msgs::GetLocationsByStringResponse_<std::allocator<void> > GetLocationsByStringResponse;

typedef boost::shared_ptr< ::hypermap_msgs::GetLocationsByStringResponse > GetLocationsByStringResponsePtr;
typedef boost::shared_ptr< ::hypermap_msgs::GetLocationsByStringResponse const> GetLocationsByStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.locations == rhs.locations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hypermap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d45bf911fc03811b8b5d44e79e15058f";
  }

  static const char* value(const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd45bf911fc03811bULL;
  static const uint64_t static_value2 = 0x8b5d44e79e15058fULL;
};

template<class ContainerAllocator>
struct DataType< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hypermap_msgs/GetLocationsByStringResponse";
  }

  static const char* value(const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] locations\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.locations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLocationsByStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hypermap_msgs::GetLocationsByStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETLOCATIONSBYSTRINGRESPONSE_H
