// Generated by gencpp from file hypermap_msgs/GetSemanticByAreaRequest.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREAREQUEST_H
#define HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>

namespace hypermap_msgs
{
template <class ContainerAllocator>
struct GetSemanticByAreaRequest_
{
  typedef GetSemanticByAreaRequest_<ContainerAllocator> Type;

  GetSemanticByAreaRequest_()
    : area()  {
    }
  GetSemanticByAreaRequest_(const ContainerAllocator& _alloc)
    : area(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSemanticByAreaRequest_

typedef ::hypermap_msgs::GetSemanticByAreaRequest_<std::allocator<void> > GetSemanticByAreaRequest;

typedef boost::shared_ptr< ::hypermap_msgs::GetSemanticByAreaRequest > GetSemanticByAreaRequestPtr;
typedef boost::shared_ptr< ::hypermap_msgs::GetSemanticByAreaRequest const> GetSemanticByAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator1> & lhs, const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hypermap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "346777753e4e847f0ac4908465dae9df";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x346777753e4e847fULL;
  static const uint64_t static_value2 = 0x0ac4908465dae9dfULL;
};

template<class ContainerAllocator>
struct DataType< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hypermap_msgs/GetSemanticByAreaRequest";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PolygonStamped area\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSemanticByAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hypermap_msgs::GetSemanticByAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREAREQUEST_H
