// Generated by gencpp from file hypermap_msgs/GetStringAtPoint.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETSTRINGATPOINT_H
#define HYPERMAP_MSGS_MESSAGE_GETSTRINGATPOINT_H

#include <ros/service_traits.h>


#include <hypermap_msgs/GetStringAtPointRequest.h>
#include <hypermap_msgs/GetStringAtPointResponse.h>


namespace hypermap_msgs
{

struct GetStringAtPoint
{

typedef GetStringAtPointRequest Request;
typedef GetStringAtPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStringAtPoint
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::GetStringAtPoint > {
  static const char* value()
  {
    return "6506da1882bf4a49b3b562d98d4687c4";
  }

  static const char* value(const ::hypermap_msgs::GetStringAtPoint&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::GetStringAtPoint > {
  static const char* value()
  {
    return "hypermap_msgs/GetStringAtPoint";
  }

  static const char* value(const ::hypermap_msgs::GetStringAtPoint&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::GetStringAtPointRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetStringAtPoint >
template<>
struct MD5Sum< ::hypermap_msgs::GetStringAtPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetStringAtPoint >::value();
  }
  static const char* value(const ::hypermap_msgs::GetStringAtPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetStringAtPointRequest> should match
// service_traits::DataType< ::hypermap_msgs::GetStringAtPoint >
template<>
struct DataType< ::hypermap_msgs::GetStringAtPointRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetStringAtPoint >::value();
  }
  static const char* value(const ::hypermap_msgs::GetStringAtPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::GetStringAtPointResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetStringAtPoint >
template<>
struct MD5Sum< ::hypermap_msgs::GetStringAtPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetStringAtPoint >::value();
  }
  static const char* value(const ::hypermap_msgs::GetStringAtPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetStringAtPointResponse> should match
// service_traits::DataType< ::hypermap_msgs::GetStringAtPoint >
template<>
struct DataType< ::hypermap_msgs::GetStringAtPointResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetStringAtPoint >::value();
  }
  static const char* value(const ::hypermap_msgs::GetStringAtPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETSTRINGATPOINT_H
