// Generated by gencpp from file hypermap_msgs/GetSemanticByArea.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREA_H
#define HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREA_H

#include <ros/service_traits.h>


#include <hypermap_msgs/GetSemanticByAreaRequest.h>
#include <hypermap_msgs/GetSemanticByAreaResponse.h>


namespace hypermap_msgs
{

struct GetSemanticByArea
{

typedef GetSemanticByAreaRequest Request;
typedef GetSemanticByAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSemanticByArea
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByArea > {
  static const char* value()
  {
    return "e0c98eff6480f8c467490b1909de5d07";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByArea&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::GetSemanticByArea > {
  static const char* value()
  {
    return "hypermap_msgs/GetSemanticByArea";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByArea&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByAreaRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByArea >
template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetSemanticByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetSemanticByAreaRequest> should match
// service_traits::DataType< ::hypermap_msgs::GetSemanticByArea >
template<>
struct DataType< ::hypermap_msgs::GetSemanticByAreaRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetSemanticByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByAreaResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByArea >
template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetSemanticByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetSemanticByAreaResponse> should match
// service_traits::DataType< ::hypermap_msgs::GetSemanticByArea >
template<>
struct DataType< ::hypermap_msgs::GetSemanticByAreaResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetSemanticByArea >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYAREA_H
