// Generated by gencpp from file hypermap_msgs/GetSemanticByString.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYSTRING_H
#define HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYSTRING_H

#include <ros/service_traits.h>


#include <hypermap_msgs/GetSemanticByStringRequest.h>
#include <hypermap_msgs/GetSemanticByStringResponse.h>


namespace hypermap_msgs
{

struct GetSemanticByString
{

typedef GetSemanticByStringRequest Request;
typedef GetSemanticByStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSemanticByString
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByString > {
  static const char* value()
  {
    return "dc1a1b37336827be86f9f0f1fe2b5c16";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByString&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::GetSemanticByString > {
  static const char* value()
  {
    return "hypermap_msgs/GetSemanticByString";
  }

  static const char* value(const ::hypermap_msgs::GetSemanticByString&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByStringRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByString >
template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetSemanticByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetSemanticByStringRequest> should match
// service_traits::DataType< ::hypermap_msgs::GetSemanticByString >
template<>
struct DataType< ::hypermap_msgs::GetSemanticByStringRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetSemanticByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByStringResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::GetSemanticByString >
template<>
struct MD5Sum< ::hypermap_msgs::GetSemanticByStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::GetSemanticByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::GetSemanticByStringResponse> should match
// service_traits::DataType< ::hypermap_msgs::GetSemanticByString >
template<>
struct DataType< ::hypermap_msgs::GetSemanticByStringResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::GetSemanticByString >::value();
  }
  static const char* value(const ::hypermap_msgs::GetSemanticByStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_GETSEMANTICBYSTRING_H
