// Generated by gencpp from file hypermap_msgs/LoadMap.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_LOADMAP_H
#define HYPERMAP_MSGS_MESSAGE_LOADMAP_H

#include <ros/service_traits.h>


#include <hypermap_msgs/LoadMapRequest.h>
#include <hypermap_msgs/LoadMapResponse.h>


namespace hypermap_msgs
{

struct LoadMap
{

typedef LoadMapRequest Request;
typedef LoadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMap
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::LoadMap > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::hypermap_msgs::LoadMap&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::LoadMap > {
  static const char* value()
  {
    return "hypermap_msgs/LoadMap";
  }

  static const char* value(const ::hypermap_msgs::LoadMap&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::LoadMapRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::LoadMap >
template<>
struct MD5Sum< ::hypermap_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::LoadMap >::value();
  }
  static const char* value(const ::hypermap_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::LoadMapRequest> should match
// service_traits::DataType< ::hypermap_msgs::LoadMap >
template<>
struct DataType< ::hypermap_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::LoadMap >::value();
  }
  static const char* value(const ::hypermap_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::LoadMapResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::LoadMap >
template<>
struct MD5Sum< ::hypermap_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::LoadMap >::value();
  }
  static const char* value(const ::hypermap_msgs::LoadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::LoadMapResponse> should match
// service_traits::DataType< ::hypermap_msgs::LoadMap >
template<>
struct DataType< ::hypermap_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::LoadMap >::value();
  }
  static const char* value(const ::hypermap_msgs::LoadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_LOADMAP_H
