// Generated by gencpp from file hypermap_msgs/SemanticMap.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_SEMANTICMAP_H
#define HYPERMAP_MSGS_MESSAGE_SEMANTICMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hypermap_msgs/SemanticObject.h>

namespace hypermap_msgs
{
template <class ContainerAllocator>
struct SemanticMap_
{
  typedef SemanticMap_<ContainerAllocator> Type;

  SemanticMap_()
    : header()
    , objects()  {
    }
  SemanticMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hypermap_msgs::SemanticObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hypermap_msgs::SemanticObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::hypermap_msgs::SemanticMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hypermap_msgs::SemanticMap_<ContainerAllocator> const> ConstPtr;

}; // struct SemanticMap_

typedef ::hypermap_msgs::SemanticMap_<std::allocator<void> > SemanticMap;

typedef boost::shared_ptr< ::hypermap_msgs::SemanticMap > SemanticMapPtr;
typedef boost::shared_ptr< ::hypermap_msgs::SemanticMap const> SemanticMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hypermap_msgs::SemanticMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hypermap_msgs::SemanticMap_<ContainerAllocator1> & lhs, const ::hypermap_msgs::SemanticMap_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hypermap_msgs::SemanticMap_<ContainerAllocator1> & lhs, const ::hypermap_msgs::SemanticMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hypermap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hypermap_msgs::SemanticMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hypermap_msgs::SemanticMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hypermap_msgs::SemanticMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ec6a1e8bd790c8b760fdac54437cce7";
  }

  static const char* value(const ::hypermap_msgs::SemanticMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ec6a1e8bd790c8bULL;
  static const uint64_t static_value2 = 0x760fdac54437cce7ULL;
};

template<class ContainerAllocator>
struct DataType< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hypermap_msgs/SemanticMap";
  }

  static const char* value(const ::hypermap_msgs::SemanticMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"SemanticObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hypermap_msgs/SemanticObject\n"
"int32 id\n"
"geometry_msgs/Polygon shape\n"
"geometry_msgs/Point position # should be centroid of shape\n"
"string name\n"
"string[] tags\n"
"float64[] confidence\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hypermap_msgs::SemanticMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SemanticMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hypermap_msgs::SemanticMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hypermap_msgs::SemanticMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hypermap_msgs::SemanticObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_SEMANTICMAP_H
