// Generated by gencpp from file hypermap_msgs/StoreMap.msg
// DO NOT EDIT!


#ifndef HYPERMAP_MSGS_MESSAGE_STOREMAP_H
#define HYPERMAP_MSGS_MESSAGE_STOREMAP_H

#include <ros/service_traits.h>


#include <hypermap_msgs/StoreMapRequest.h>
#include <hypermap_msgs/StoreMapResponse.h>


namespace hypermap_msgs
{

struct StoreMap
{

typedef StoreMapRequest Request;
typedef StoreMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StoreMap
} // namespace hypermap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hypermap_msgs::StoreMap > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::hypermap_msgs::StoreMap&) { return value(); }
};

template<>
struct DataType< ::hypermap_msgs::StoreMap > {
  static const char* value()
  {
    return "hypermap_msgs/StoreMap";
  }

  static const char* value(const ::hypermap_msgs::StoreMap&) { return value(); }
};


// service_traits::MD5Sum< ::hypermap_msgs::StoreMapRequest> should match
// service_traits::MD5Sum< ::hypermap_msgs::StoreMap >
template<>
struct MD5Sum< ::hypermap_msgs::StoreMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::StoreMap >::value();
  }
  static const char* value(const ::hypermap_msgs::StoreMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::StoreMapRequest> should match
// service_traits::DataType< ::hypermap_msgs::StoreMap >
template<>
struct DataType< ::hypermap_msgs::StoreMapRequest>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::StoreMap >::value();
  }
  static const char* value(const ::hypermap_msgs::StoreMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hypermap_msgs::StoreMapResponse> should match
// service_traits::MD5Sum< ::hypermap_msgs::StoreMap >
template<>
struct MD5Sum< ::hypermap_msgs::StoreMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hypermap_msgs::StoreMap >::value();
  }
  static const char* value(const ::hypermap_msgs::StoreMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hypermap_msgs::StoreMapResponse> should match
// service_traits::DataType< ::hypermap_msgs::StoreMap >
template<>
struct DataType< ::hypermap_msgs::StoreMapResponse>
{
  static const char* value()
  {
    return DataType< ::hypermap_msgs::StoreMap >::value();
  }
  static const char* value(const ::hypermap_msgs::StoreMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYPERMAP_MSGS_MESSAGE_STOREMAP_H
