(cl:defpackage mapping_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<BOUNDINGBOXES>"
   "BOUNDINGBOXES"
   "<BOXESANDCLOUDS>"
   "BOXESANDCLOUDS"
   "<FINDOBJECTS>"
   "FINDOBJECTS"
   "<OBBMAP>"
   "OBBMAP"
   "<OBJECTCOUNT>"
   "OBJECTCOUNT"
   "<OBJECTPOSITIONS>"
   "OBJECTPOSITIONS"
   "<SEMANTICMAP>"
   "SEMANTICMAP"
   "<SEMANTICOBJECT>"
   "SEMANTICOBJECT"
  ))

